# -*- coding: utf-8 -*-
"""Atividade12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MNh14fCSt5I1EXdmVIwrkk57chlgcrj-
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

file_path = 'heart.csv'
df = pd.read_csv(file_path)

print(data.columns)

age = df['age'].tolist()
sex = df['sex'].tolist()
cp = df['cp'].tolist()
trtbps = df['trtbps'].tolist()
chol = df['chol'].tolist()
fbs = df['fbs'].tolist()

output = df['output'].tolist()

age = np.array(age)
sex = np.array(sex)
cp = np.array(cp)
trtbps = np.array(trtbps)
chol = np.array(chol)
fbs = np.array(fbs)
output = np.array(output)

X = np.column_stack((age, sex, cp, trtbps, chol, fbs))
y = output

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()

model.fit(X_train, y_train)

score = model.score(X_test, y_test)
print(f'Score do modelo: {score}')

predictions = model.predict(X_test)
print(f'Predições: {predictions}')

plt.scatter(X_test[:, 0], y_test, color='blue', label='Dados Reais')
plt.scatter(X_test[:, 0], predictions, color='red', label='Predições')
plt.xlabel('Age')
plt.ylabel('Output')
plt.legend()
plt.title('Predição de Ataque Cardíaco')
plt.show()