# -*- coding: utf-8 -*-
"""Atividade11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y31nORzi5m15FjDAVJv53OMxLMbP-FTC
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

df = pd.read_csv('weatherAUS.csv')
df = df.dropna(subset=['MinTemp', 'MaxTemp', 'Rainfall'])

temperatura_minima = df['MinTemp'].tolist()
temperatura_maxima = df['MaxTemp'].tolist()
rainfall = df['Rainfall'].tolist()

X = np.array(list(zip(temperatura_minima, temperatura_maxima)))
y = np.array([1 if x > 0 else 0 for x in rainfall])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

modelo = LogisticRegression()

modelo.fit(X_train, y_train)

score = modelo.score(X_test, y_test)
print(f'Score do modelo: {score}')

X_new = np.array([[10, 20], [15, 25], [20, 30]])
print(X_new)

predictions = modelo.predict(X_new)
print(f'Predições: {predictions}')

pred_probabilities = modelo.predict_proba(X_new)
print(f'Probabilidades de predição: {pred_probabilities}')

y_pred = modelo.predict(X_test)

plt.scatter(X_test[:, 1], y_test, color='blue', label='Dados Reais')
plt.scatter(X_test[:, 1], y_pred, color='red', label='Predições')
plt.xlabel('Temperatura Máxima')
plt.ylabel('Chuva (0 = Não, 1 = Sim)')
plt.legend()
plt.show()